# Generated by Django 6.1.2 on 2026-10-07 02:51

import django.core.validators
import django.db.models.deletion
import troubleshooting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='troubleshooting/products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), troubleshooting.models.validate_image_size])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='troubleshooting.productrange')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='troubleshooting.problem')),
            ],
            options={
                'ordering': ('problem__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('step_type', models.CharField(choices=[('instruction', 'Instruction'), ('question', 'Question / decision'), ('inspection', 'Inspection'), ('resolution', 'Resolution'), ('download', 'Downloadable procedure')], default='instruction', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('warning', models.TextField(blank=True)),
                ('guide_file', models.FileField(blank=True, upload_to='troubleshooting/guides/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx')), troubleshooting.models.validate_guide_size])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='troubleshooting.troubleshootingflow')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='troubleshootingflow',
            name='start_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starting_flows', to='troubleshooting.troubleshootingstep'),
        ),
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='troubleshooting/steps/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), troubleshooting.models.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='troubleshooting.troubleshootingstep')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StepChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_choices', to='troubleshooting.troubleshootingstep')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='troubleshooting.troubleshootingstep')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('product_range', 'name'), name='unique_problem_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='troubleshootingflow',
            constraint=models.UniqueConstraint(fields=('problem', 'name'), name='unique_flow_name_per_problem'),
        ),
        migrations.AddConstraint(
            model_name='stepchoice',
            constraint=models.UniqueConstraint(fields=('step', 'label'), name='unique_choice_label_per_step'),
        ),
    ]
