# Generated by Django 6.1.2 on 2026-10-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleshooting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConfigurationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_questions', to='troubleshooting.configurationoption')),
                ('product_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_questions', to='troubleshooting.productrange')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='configurationoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='troubleshooting.configurationquestion'),
        ),
        migrations.CreateModel(
            name='FlowConfigurationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_requirements', to='troubleshooting.troubleshootingflow')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_requirements', to='troubleshooting.configurationoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='configurationoption',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='unique_configuration_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='flowconfigurationrequirement',
            constraint=models.UniqueConstraint(fields=('flow', 'option'), name='unique_configuration_requirement_per_flow'),
        ),
    ]
