# Generated by Django 6.1.2 on 2026-10-07 06:34

import django.db.models.deletion
from django.db import migrations, models


def preserve_question_scopes_and_add_products(apps, schema_editor):
    ProductRange = apps.get_model('troubleshooting', 'ProductRange')
    ConfigurationQuestion = apps.get_model(
        'troubleshooting',
        'ConfigurationQuestion',
    )
    database = schema_editor.connection.alias
    product_names = ('VSAT', 'Starlink', 'OneWeb', 'Mobile')
    products = []

    for sort_order, name in enumerate(product_names):
        product = ProductRange.objects.using(database).get_or_create(
            name=name,
            defaults={'sort_order': sort_order, 'is_active': True},
        )[0]
        products.append(product)

    # Preserve existing product-specific questions and make legacy global
    # questions explicitly applicable to products already in the catalog.
    for question in ConfigurationQuestion.objects.using(database).all():
        if question.product_range_id is not None:
            question.applies_to_products.add(question.product_range_id)
        else:
            question.applies_to_products.add(*[product.pk for product in products])


class Migration(migrations.Migration):

    dependencies = [
        ('troubleshooting', '0002_configurationoption_configurationquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationquestion',
            name='applies_to_products',
            field=models.ManyToManyField(blank=True, related_name='configuration_questions', to='troubleshooting.productrange'),
        ),
        migrations.AddField(
            model_name='configurationquestion',
            name='phase',
            field=models.CharField(choices=[('setup', 'System configuration'), ('diagnosis', 'Problem diagnosis')], default='setup', max_length=12),
        ),
        migrations.AddField(
            model_name='configurationquestion',
            name='problem',
            field=models.ForeignKey(blank=True, help_text='Optional: limit a diagnostic question to one problem.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_questions', to='troubleshooting.problem'),
        ),
        migrations.RunPython(
            preserve_question_scopes_and_add_products,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='configurationquestion',
            name='product_range',
        ),
    ]
