"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _environment_flag(name, default):
    """Parse a security-related environment flag without accepting typos."""
    value = os.environ.get(name)
    if value is None:
        return default

    normalized_value = value.strip().lower()
    if normalized_value in {'true', '1', 'yes', 'on'}:
        return True
    if normalized_value in {'false', '0', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(f'{name} must be set to true or false.')


# Local development stays convenient; deployments must explicitly disable debug.
DEBUG = _environment_flag('DJANGO_DEBUG', default=True)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

# Require both a stable secret and an explicit host allowlist in production.
if not DEBUG:
    if not SECRET_KEY:
        raise ImproperlyConfigured(
            'Set DJANGO_SECRET_KEY when DJANGO_DEBUG is disabled.',
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'Set DJANGO_ALLOWED_HOSTS when DJANGO_DEBUG is disabled.',
        )
elif not SECRET_KEY:
    # A random development-only key avoids storing a reusable secret in source.
    SECRET_KEY = get_random_secret_key()

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Production cookies and HTTPS redirects are enabled unless explicitly overridden.
SECURE_SSL_REDIRECT = _environment_flag(
    'DJANGO_SECURE_SSL_REDIRECT',
    default=not DEBUG,
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _environment_flag(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=False,
)
SECURE_HSTS_PRELOAD = _environment_flag(
    'DJANGO_SECURE_HSTS_PRELOAD',
    default=False,
)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

# Enable only behind a proxy that replaces, rather than forwards, this header.
if _environment_flag('DJANGO_TRUST_X_FORWARDED_PROTO', default=False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Registers the database-backed troubleshooting content models.
    'troubleshooting.apps.TroubleshootingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Store administrator-uploaded files outside the source code directories.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Guide pages and procedure files are available only after user authentication.
LOGIN_URL = 'troubleshooting:login'
LOGIN_REDIRECT_URL = 'troubleshooting:product_list'
LOGOUT_REDIRECT_URL = 'troubleshooting:home'


# Keep email visible in local development and use SMTP by default outside it.
email_backend = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    (
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG
        else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
email_host = os.environ.get('DJANGO_EMAIL_HOST', '')
if (
    not DEBUG
    and email_backend == 'django.core.mail.backends.smtp.EmailBackend'
    and not email_host
):
    raise ImproperlyConfigured(
        'Set DJANGO_EMAIL_HOST when SMTP is the production email backend.',
    )

email_options = {}
if email_backend == 'django.core.mail.backends.smtp.EmailBackend':
    # MAILERS passes OPTIONS directly to the selected backend constructor.
    email_options = {
        'host': email_host,
        'port': int(os.environ.get('DJANGO_EMAIL_PORT', '587')),
        'username': os.environ.get('DJANGO_EMAIL_HOST_USER') or None,
        'password': os.environ.get('DJANGO_EMAIL_HOST_PASSWORD') or None,
        'use_tls': _environment_flag('DJANGO_EMAIL_USE_TLS', default=not DEBUG),
        'use_ssl': _environment_flag('DJANGO_EMAIL_USE_SSL', default=False),
        'timeout': int(os.environ.get('DJANGO_EMAIL_TIMEOUT', '10')),
    }

MAILERS = {
    'default': {
        'BACKEND': email_backend,
        'OPTIONS': email_options,
    },
}

# SMTP credentials stay in deployment environment variables, never in source.
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL',
    'webmaster@localhost',
)
